# Generated by Django 2.0 on 2017-12-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, height_field=75, upload_to='images/avatars/%Y/%m/%d', width_field=75),
        ),
    ]
