# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypermarket', '0002_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=None, upload_to='hypermarket/static/media/images/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
