# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypermarket', '0003_auto_20171208_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=None, upload_to='%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
