# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hypermarket', '0004_auto_20171208_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='file////C:/Users/MSI-PNoryk/Desktop/site/NoPicAvailable.png',
                                    upload_to='images/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
