# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypermarket', '0005_auto_20171208_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Input title text', max_length=255),
        ),
    ]
