# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypermarket', '0009_auto_20171213_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='images/NoPicAvailable.png', height_field=150, upload_to='images/%Y/%m/%d', verbose_name='Ссылка картинки', width_field=150),
        ),
    ]
