# Generated by Django 2.0 on 2017-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171217_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
