# Generated by Django 2.0 on 2017-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20171217_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='product_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='total_price'),
        ),
    ]
