# Generated by Django 2.0 on 2017-12-18 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20171218_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='New', max_length=25),
        ),
    ]
