# Generated by Django 2.0 on 2017-12-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20171218_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
