# Generated by Django 2.0 on 2017-12-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20171218_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='updated',
        ),
    ]
