# Generated by Django 2.0 on 2017-12-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_status_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='New', on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Status'),
        ),
    ]
