# Generated by Django 2.0 on 2017-12-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
