# Generated by Django 2.0 on 2017-12-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171218_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='New', on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductCategory'),
        ),
    ]
