# Generated by Django 2.1.1 on 2018-12-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20171218_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-id'], 'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
    ]
